#! /usr/bin/bash

TODO_FILE=$SCRIPTS/todos.txt


print_todos() {
    if [ -s $TODO_FILE ]; then
    echo "`cat $TODO_FILE | sed s/OPEN/[" "]/ | sed s/CLOSED/[X]/`";
    else
        echo "You have nothing TODO"
    fi;

}

watch_todos() {
    if ! command -v entr &> /dev/null
    then 
        echo "watch requires entr to run -> http://eradman.com/entrproject/"
    fi
    echo $TODO_FILE | entr todos 
}

print_help() {
    echo "Prints todos"
    echo " "
    echo "options:"
    echo "-h --help            show this help message"
    echo "-w --watch           watch todos for changes"
}

## Print the TODOs if no argument is passed
if [ $# -eq 0 ]; then
    clear;
    print_todos;
    exit 1
fi

case "$1" in
    -w|--watch) watch_todos ;;
    -h|--help) print_help ;;
    *) echo "invalid flag" ; print_help ;;
esac
