#! /usr/bin/bash

## Simple TODO script

TODO_FILE=$HOME/todos.txt

if [ ! -f $TODO_FILE ]; then
    touch $TODO_FILE
fi


## Base functions
create_todo() {
    local MSG=$1
    BIGGEST_ID=0;
    local TODOS=$(cat $TODO_FILE)
    local IDS=`echo "$TODOS" | awk '{print $1;}'`
    for ID in $IDS; do
        if [ $ID -gt $BIGGEST_ID ]; then
            BIGGEST_ID=$ID;
        fi
    done;
    local NEW_ID=$(( BIGGEST_ID + 1 ))
    echo "$NEW_ID OPEN $MSG" >> $TODO_FILE 
}

complete_todo() {
    local ARG_IDS=$*
    local TODOS=$(cat $TODO_FILE)

    local TODO_IDS=`echo "$TODOS" | awk '{print $1;}'`
    for ARG_ID in $ARG_IDS; do
        local ARR_INDEX=1
        for ID in $TODO_IDS; do
            if [ "$ID" == "$ARG_ID" ]; then
                sed -i "${ARR_INDEX}s/OPEN/CLOSED/" $TODO_FILE
            fi;
            ARR_INDEX=$((ARR_INDEX + 1));
        done;
    done;
}

reopen_todo() {
    local ARG_IDS=$*
    local TODOS=$(cat $TODO_FILE)

    local TODO_IDS=`echo "$TODOS" | awk '{print $1;}'`
    for ARG_ID in $ARG_IDS; do
        local ARR_INDEX=1
        for ID in $TODO_IDS; do
            if [ "$ID" == "$ARG_ID" ]; then
                sed -i "${ARR_INDEX}s/CLOSED/OPEN/" $TODO_FILE
            fi;
            ARR_INDEX=$((ARR_INDEX + 1))
        done;
    done;
}

remove_todo() {
    local ARG_IDS=$*
    local TODOS=$(cat $TODO_FILE)

    local TODO_IDS=`echo "$TODOS" | awk '{print $1;}'`
    for ARG_ID in $ARG_IDS; do
        for ID in $TODO_IDS; do
            if [ "$ID" == "$ARG_ID" ]; then
                sed -i /$ID/d $TODO_FILE
            fi;
        done;
    done;
}

clear_todos() {
    truncate -s 0 $TODO_FILE
}



print_help() {
    echo "Edit list of todos"
    echo " "
    echo 'Called without args it will create a TODO -> todo "do something"'
    echo "TODOs can be viewed using the command 'todos'" 
    echo " "
    echo "options:"
    echo "-d --done [IDS]      marks one or more TODOs as done"
    echo "-o --open [IDS]      reopens one or more close TODOs"
    echo "-r --remove [IDS]    removes one or more TODOs from the list"
    echo "-c --clear           clear the list of TODOs"
    echo "-h --help            prints this help message"
}

FIRST_ARG=$1

## If no flag is given create TODO with given arg
if [ ! ${FIRST_ARG:0:1} == "-" ]; then
    create_todo "$1"
    exit 1;
fi

## Check provided flags add call relevant function
case "$1" in
    -d|--done)
        ALL_ARGS="$*"
        ID_LIST=`echo "$ALL_ARGS" | cut -d' ' -f2-`
        complete_todo "$ID_LIST"
        ;;
    -o|--open)
        ALL_ARGS="$*"
        ID_LIST=`echo "$ALL_ARGS" | cut -d' ' -f2-`
        reopen_todo "$ID_LIST"
        ;;
    -r|--remove)
        ALL_ARGS="$*"
        ID_LIST=`echo "$ALL_ARGS" | cut -d' ' -f2-`
        remove_todo "$ID_LIST"
        ;;
    -c|--clear)
        clear_todos
        ;;
    -h|--help)
       print_help 
        ;;
    *)
      echo "Invalid flag"
      print_help
      ;;
esac
